language: csharp
solution: PlexureAPITest.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore PlexureAPITest.sln
after_script:
  - nunit-console ./PlexureAPITest/bin/Debug/PlexureAPITest.dll
