language: csharp
solution: PlexureAPITest.sln
install:
  - nuget restore PlexureAPITest.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release PlexureAPITest.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./PlexureAPITest/bin/Debug/PlexureAPITest.dll
